import type { Metadata } from "next";
import { Fira_Code, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/features/navbar";
import Footer from "./components/features/footer";
import { CartProvider } from "@/app/context/cart-context";

const firaCode = Fira_Code({
  variable: "--font-fira",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${firaCode.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <CartProvider>
          {" "}
          {/* ← add this */}
          <Navbar />
          {children}
          <Footer />
        </CartProvider>{" "}
        {/* ← and this */}
      </body>
    </html>
  );
}
